import { Student } from "@/entities/student/types";

export const studentsData: Student[] = [
  {
    id: 1,
    fullName: "Кванов Иван Иванович",
    company: "ООО «Рога и копыта»",
    startDateWork: "2025-05-13",
    position: "Стажер",
  },
  {
    id: 2,
    fullName: "Иванов Иван",
    company: "ООО «Рога и копыта»",
    startDateWork: "2023-05-13",
    position: "Стажер",
  },
  {
    id: 3,
    fullName: "Ивов Иван Иванович",
    company: "ООО «Рога и копыта»",
    startDateWork: "2025-03-13",
    position: "Стажер",
  },
  {
    id: 4,
    fullName: "Иванов Иван",
    company: "ООО «Рога и копыта»",
    startDateWork: "2025-05-13",
    position: "Стажер",
  },
  {
    id: 5,
    fullName: "Иватов Иван",
    company: "ООО «Рога и копыта»",
    startDateWork: "2025-05-13",
    position: "Стажер",
  },
  {
    id: 6,
    fullName: "Иватов Иван",
    company: "ООО «Рога и копыта»",
    startDateWork: "2025-05-13",
    position: "Стажер",
  },
  {
    id: 7,
    fullName: "Иватов Иван",
    company: "ООО «Рога и копыта»",
    startDateWork: "2025-05-13",
    position: "Стажер",
  },
  {
    id: 8,
    fullName: "Иватов Иван",
    company: "ООО «Рога и копыта»",
    startDateWork: "2025-05-13",
    position: "Стажер",
  },
  {
    id: 9,
    fullName: "Иватов Иван",
    company: "ООО «Рога и копыта»",
    startDateWork: "2025-05-13",
    position: "Стажер",
  },
  {
    id: 10,
    fullName: "Иватов Иван",
    company: "ООО «Рога и копыта»",
    startDateWork: "2025-05-13",
    position: "Стажер",
  },
  {
    id: 11,
    fullName: "Иватов Иван",
    company: "ООО «Рога и копыта»",
    startDateWork: "2025-05-13",
    position: "Стажер",
  },
  {
    id: 12,
    fullName: "Иватов Иван",
    company: "ООО «Рога и копыта»",
    startDateWork: "2025-05-13",
    position: "Стажер",
  },
  {
    id: 13,
    fullName: "Иватов Иван",
    company: "ООО «Рога и копыта»",
    startDateWork: "2025-05-13",
    position: "Стажер",
  },
  {
    id: 14,
    fullName: "Иватов Иван",
    company: "ООО «Рога и копыта»",
    startDateWork: "2025-05-13",
    position: "Стажер",
  },
  {
    id: 15,
    fullName: "Иватов Иван",
    company: "ООО «Рога и копыта»",
    startDateWork: "2025-05-13",
    position: "Стажер",
  },
  {
    id: 16,
    fullName: "Иватов Иван",
    company: "ООО «Рога и копыта»",
    startDateWork: "2025-05-13",
    position: "Стажер",
  },
  {
    id: 17,
    fullName: "Иватов Иван",
    company: "ООО «Рога и копыта»",
    startDateWork: "2025-05-13",
    position: "Стажер",
  },
  {
    id: 18,
    fullName: "Иватов Иван",
    company: "ООО «Рога и копыта»",
    startDateWork: "2025-05-13",
    position: "Стажер",
  },
  {
    id: 19,
    fullName: "Иватов Иван",
    company: "ООО «Рога и копыта»",
    startDateWork: "2025-05-13",
    position: "Стажер",
  },
  {
    id: 20,
    fullName: "Иватов Иван",
    company: "ООО «Рога и копыта»",
    startDateWork: "2025-05-13",
    position: "Стажер",
  },
  {
    id: 21,
    fullName: "Иватов Иван",
    company: "ООО «Рога и копыта»",
    startDateWork: "2025-05-13",
    position: "Стажер",
  },
  {
    id: 22,
    fullName: "Иватов Иван",
    company: "ООО «Рога и копыта»",
    startDateWork: "2025-05-13",
    position: "Стажер",
  },
  {
    id: 23,
    fullName: "Иватов Иван",
    company: "ООО «Рога и копыта»",
    startDateWork: "2025-05-13",
    position: "Стажер",
  },
];
