// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add_SubjectByGroupId(arg1, arg2) {
  return window["go"]["main"]["App"]["Add_SubjectByGroupId"](arg1, arg2);
}

export function Create_Group(arg1, arg2, arg3, arg4, arg5) {
  return window["go"]["main"]["App"]["Create_Group"](
    arg1,
    arg2,
    arg3,
    arg4,
    arg5,
  );
}

export function Create_Student(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window["go"]["main"]["App"]["Create_Student"](
    arg1,
    arg2,
    arg3,
    arg4,
    arg5,
    arg6,
  );
}

export function Delete_AllSubjectByGroupId(arg1) {
  return window["go"]["main"]["App"]["Delete_AllSubjectByGroupId"](arg1);
}

export function Delete_EmpbyStudentId(arg1) {
  return window["go"]["main"]["App"]["Delete_EmpbyStudentId"](arg1);
}

export function Delete_GroupById(arg1) {
  return window["go"]["main"]["App"]["Delete_GroupById"](arg1);
}

export function Delete_Student(arg1) {
  return window["go"]["main"]["App"]["Delete_Student"](arg1);
}

export function Delete_SubjectById(arg1) {
  return window["go"]["main"]["App"]["Delete_SubjectById"](arg1);
}

export function GenerateFilledPDF(arg1, arg2, arg3) {
  return window["go"]["main"]["App"]["GenerateFilledPDF"](arg1, arg2, arg3);
}

export function GetGroupId_GroupIdByInfo(arg1, arg2, arg3, arg4, arg5) {
  return window["go"]["main"]["App"]["GetGroupId_GroupIdByInfo"](
    arg1,
    arg2,
    arg3,
    arg4,
    arg5,
  );
}

export function Greet(arg1) {
  return window["go"]["main"]["App"]["Greet"](arg1);
}

export function Inf_AllGroup() {
  return window["go"]["main"]["App"]["Inf_AllGroup"]();
}

export function Inf_AllStudent() {
  return window["go"]["main"]["App"]["Inf_AllStudent"]();
}

export function Inf_EmpByStudentId(arg1) {
  return window["go"]["main"]["App"]["Inf_EmpByStudentId"](arg1);
}

export function Inf_StudentByID(arg1) {
  return window["go"]["main"]["App"]["Inf_StudentByID"](arg1);
}

export function Inf_SubjectByGroupId(arg1) {
  return window["go"]["main"]["App"]["Inf_SubjectByGroupId"](arg1);
}

export function Update_EmpbyStudentId(arg1, arg2, arg3, arg4) {
  return window["go"]["main"]["App"]["Update_EmpbyStudentId"](
    arg1,
    arg2,
    arg3,
    arg4,
  );
}

export function Update_GroupById(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window["go"]["main"]["App"]["Update_GroupById"](
    arg1,
    arg2,
    arg3,
    arg4,
    arg5,
    arg6,
  );
}

export function Update_StudentById(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window["go"]["main"]["App"]["Update_StudentById"](
    arg1,
    arg2,
    arg3,
    arg4,
    arg5,
    arg6,
    arg7,
  );
}

export function Update_SubjectById(arg1, arg2) {
  return window["go"]["main"]["App"]["Update_SubjectById"](arg1, arg2);
}
