// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {modeles} from '../models';

export function Add_SubjectByGroupId(arg1:number,arg2:string):Promise<modeles.Create>;

export function Create_Group(arg1:number,arg2:number,arg3:string,arg4:number,arg5:number):Promise<modeles.Create>;

export function Create_Student(arg1:string,arg2:number,arg3:number,arg4:string,arg5:number,arg6:number):Promise<modeles.Create>;

export function Delete_AllSubjectByGroupId(arg1:number):Promise<modeles.Remove>;

export function Delete_EmpbyStudentId(arg1:number):Promise<modeles.Remove>;

export function Delete_GroupById(arg1:number):Promise<modeles.Remove>;

export function Delete_Student(arg1:number):Promise<modeles.Remove>;

export function Delete_SubjectById(arg1:number):Promise<modeles.Remove>;

export function GenerateFilledPDF(arg1:number,arg2:string,arg3:number):Promise<modeles.PdfDock>;

export function GetGroupId_GroupIdByInfo(arg1:number,arg2:number,arg3:string,arg4:number,arg5:number):Promise<modeles.GetId>;

export function Greet(arg1:string):Promise<string>;

export function Inf_AllGroup():Promise<modeles.Inf_AllGroup>;

export function Inf_AllStudent():Promise<modeles.Inf_AllStudents>;

export function Inf_EmpByStudentId(arg1:number):Promise<modeles.Inf_Employer>;

export function Inf_StudentByID(arg1:number):Promise<modeles.Inf_Student>;

export function Inf_SubjectByGroupId(arg1:number):Promise<modeles.Inf_Subject>;

export function Update_EmpbyStudentId(arg1:number,arg2:string,arg3:string,arg4:string):Promise<modeles.Update>;

export function Update_GroupById(arg1:number,arg2:number,arg3:number,arg4:string,arg5:number,arg6:number):Promise<modeles.Update>;

export function Update_StudentById(arg1:number,arg2:string,arg3:number,arg4:number,arg5:string,arg6:number,arg7:number):Promise<modeles.Update>;

export function Update_SubjectById(arg1:number,arg2:string):Promise<modeles.Update>;
