// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import { modeles } from "../models";

export function Add_SubjectByGroupId(
  arg1: number,
  arg2: string,
): Promise<number>;

export function Create_Group(
  arg1: number,
  arg2: number,
  arg3: string,
  arg4: number,
  arg5: number,
): Promise<number>;

export function Create_Student(
  arg1: string,
  arg2: number,
  arg3: number,
  arg4: string,
  arg5: number,
  arg6: number,
): Promise<number>;

export function Delete_AllSubjectByGroupId(arg1: number): Promise<boolean>;

export function Delete_EmpbyStudentId(arg1: number): Promise<boolean>;

export function Delete_GroupById(arg1: number): Promise<boolean>;

export function Delete_Student(arg1: number): Promise<boolean>;

export function Delete_SubjectById(arg1: number): Promise<boolean>;

export function GenerateFilledPDF(
  arg1: number,
  arg2: string,
  arg3: number,
): Promise<Array<number>>;

export function GetGroupId_GroupIdByInfo(
  arg1: number,
  arg2: number,
  arg3: string,
  arg4: number,
  arg5: number,
): Promise<number>;

export function Greet(arg1: string): Promise<string>;

export function Inf_AllGroup(): Promise<Array<modeles.EinfGroup>>;

export function Inf_AllStudent(): Promise<Array<modeles.Student>>;

export function Inf_EmpByStudentId(arg1: number): Promise<modeles.EInfEmp>;

export function Inf_StudentByID(arg1: number): Promise<modeles.Student>;

export function Inf_SubjectByGroupId(arg1: number): Promise<Array<string>>;

export function Update_EmpbyStudentId(
  arg1: number,
  arg2: string,
  arg3: string,
  arg4: string,
): Promise<boolean>;

export function Update_GroupById(
  arg1: number,
  arg2: number,
  arg3: number,
  arg4: string,
  arg5: number,
  arg6: number,
): Promise<boolean>;

export function Update_StudentById(
  arg1: number,
  arg2: string,
  arg3: number,
  arg4: number,
  arg5: string,
  arg6: number,
  arg7: number,
): Promise<boolean>;

export function Update_SubjectById(
  arg1: number,
  arg2: string,
): Promise<boolean>;
